[project]
name = "wb-test"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "aiogram>=3.20.0.post0",
    "aiohttp>=3.11.18",
    "python-dotenv>=1.1.0",
    "redis>=6.1.0",
]
